
build:
  version: "2.0"

cards:
  message: "Welcome to cards related QA APIs "
  contactDetails:
    name: "Morty Smith - QA Lead"
    email: "mortysmith@gmail.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267