
build:
  version: "2.0"

loans:
  message: "Welcome to loans related QA APIs "
  contactDetails:
    name: "Morty Smith - QA Lead"
    email: "mortysmith@gmail.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467